version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./backend:/code
    ports:
        - "8000:8000"
    depends_on:
        - db
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    command: yarn dev
#    tty: true
#    restart: always
#    volumes:
#      - ./frontend:/code
#    ports:
#        - "3000:3000"
#    environment:
#      CHOKIDAR_USEPOLLING: "true"
#    depends_on:
#        - backend

